version: '3.8'

networks:
  laravel:
    name: laravel

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx
    ports:
     - 80:80
     - 443:443
    volumes:
      - ./src:/var/www/html
    networks:
    - laravel
  
  # apache:
  #   build:
  #     context: .
  #     dockerfile: apache.dockerfile
  #   container_name: apache
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - ./src:/var/www/html
  #   networks:
  #     - laravel

  php:
    image: php:7.4.33-fpm-alpine
    container_name: php
    networks:
    - laravel

  mysql:
    image: mysql:5.7.32
    container_name: mysql
    environment:
      MYSQL_DATABASE: blog
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: MYSQL_ALLOW_EMPY_PASSWORD=1
      MYSQL_PASSWORD: null
    networks:
    - laravel
